kind: pipeline
name: default

steps:
- name: build
  image: golang
  commands:
  - go build cmd/proxy/*.go
  - go test ./...
  environment:
    - GO111MODULE=on
  when:
    event:
      - push
      - pull_request