kind: pipeline
name: default

steps:
- name: build
  image: golang:1.12rc1
  commands:
  - go build cmd/proxy/*.go
  environment:
    GO111MODULE: on
  when:
    event:
      - push
      - pull_request

- name: test
  image: golang:1.12rc1
  commands:
  - go test ./...
  environment:
    GO111MODULE: on
  when:
    event:
      - push
      - pull_request
