kind: pipeline
name: default

steps:
- name: build
  image: golang:1.12rc1
  commands:
  # build
  - go build -mod=vendor cmd/proxy/*.go
  # test
  - go test -mod=vendor -v ./...
  # end to end test
  - ./main & # run the just build athens
  - sleep 3 # wait for it to spin up
  - mkdir -p ~/happy
  - mkdir -p ~/emptygopath # ensure the gopath has no modules cached.
  - cd ~/happy
  - git clone https://github.com/athens-artifacts/happy-path.git
  - cd happy-path
  - GOPATH=~/emptygopath GOPROXY=http://localhost:3000 go build
  environment:
    GO111MODULE: on
    ATHENS_MONGO_STORAGE_URL: mongodb://mongo:27017
    ATHENS_MINIO_ENDPOINT: minio:9000
  when:
    event:
      - push
      - pull_request

services:
- name: mongo
  image: mongo
  ports:
  - 27017
- name: minio
  image: minio/minio:latest
  command:
    - server
    - /data
  ports:
    - 9000
  environment:
    MINIO_ACCESS_KEY: minio
    MINIO_SECRET_KEY: minio123
    # 